name: macOS Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
      - '!*-alpha*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check repository URL
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          if [[ $REPO_URL == *"pro"* ]]; then
            exit 1
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          git describe --tags > VERSION
          REACT_APP_VERSION=$(git describe --tags) chmod u+x ./build.sh && ./build.sh
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build Backend (x86_64)
        run: |
          go mod download
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/songquanpeng/one-api/common.Version=$(git describe --tags)'" -o one-api-macos-x86_64
      - name: Build Backend (arm64)
        run: |
          go mod download
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'github.com/songquanpeng/one-api/common.Version=$(git describe --tags)'" -o one-api-macos-arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            one-api-macos-x86_64
            one-api-macos-arm64
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
